// Code generated by pg-bindings generator. DO NOT EDIT.

//go:build sql_integration

package postgres

import (
	"context"
	"testing"

	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/features"
	"github.com/stackrox/rox/pkg/postgres/pgtest"
	"github.com/stackrox/rox/pkg/sac"
	"github.com/stackrox/rox/pkg/testutils"
	"github.com/stretchr/testify/suite"
)

type ComplianceOperatorSuitesStoreSuite struct {
	suite.Suite
	store  Store
	testDB *pgtest.TestPostgres
}

func TestComplianceOperatorSuitesStore(t *testing.T) {
	suite.Run(t, new(ComplianceOperatorSuitesStoreSuite))
}

func (s *ComplianceOperatorSuitesStoreSuite) SetupSuite() {

	s.T().Setenv(features.ComplianceEnhancements.EnvVar(), "true")
	if !features.ComplianceEnhancements.Enabled() {
		s.T().Skip("Skip postgres store tests because feature flag is off")
		s.T().SkipNow()
	}

	s.testDB = pgtest.ForT(s.T())
	s.store = New(s.testDB.DB)
}

func (s *ComplianceOperatorSuitesStoreSuite) SetupTest() {
	ctx := sac.WithAllAccess(context.Background())
	tag, err := s.testDB.Exec(ctx, "TRUNCATE compliance_operator_suites CASCADE")
	s.T().Log("compliance_operator_suites", tag)
	s.store = New(s.testDB.DB)
	s.NoError(err)
}

func (s *ComplianceOperatorSuitesStoreSuite) TearDownSuite() {
	s.testDB.Teardown(s.T())
}

func (s *ComplianceOperatorSuitesStoreSuite) TestStore() {
	ctx := sac.WithAllAccess(context.Background())

	store := s.store

	complianceOperatorSuite := &storage.ComplianceOperatorSuite{}
	s.NoError(testutils.FullInit(complianceOperatorSuite, testutils.SimpleInitializer(), testutils.JSONFieldsFilter))

	foundComplianceOperatorSuite, exists, err := store.Get(ctx, complianceOperatorSuite.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundComplianceOperatorSuite)

	withNoAccessCtx := sac.WithNoAccess(ctx)

	s.NoError(store.Upsert(ctx, complianceOperatorSuite))
	foundComplianceOperatorSuite, exists, err = store.Get(ctx, complianceOperatorSuite.GetId())
	s.NoError(err)
	s.True(exists)
	s.Equal(complianceOperatorSuite, foundComplianceOperatorSuite)

	complianceOperatorSuiteCount, err := store.Count(ctx)
	s.NoError(err)
	s.Equal(1, complianceOperatorSuiteCount)
	complianceOperatorSuiteCount, err = store.Count(withNoAccessCtx)
	s.NoError(err)
	s.Zero(complianceOperatorSuiteCount)

	complianceOperatorSuiteExists, err := store.Exists(ctx, complianceOperatorSuite.GetId())
	s.NoError(err)
	s.True(complianceOperatorSuiteExists)
	s.NoError(store.Upsert(ctx, complianceOperatorSuite))
	s.ErrorIs(store.Upsert(withNoAccessCtx, complianceOperatorSuite), sac.ErrResourceAccessDenied)

	foundComplianceOperatorSuite, exists, err = store.Get(ctx, complianceOperatorSuite.GetId())
	s.NoError(err)
	s.True(exists)
	s.Equal(complianceOperatorSuite, foundComplianceOperatorSuite)

	s.NoError(store.Delete(ctx, complianceOperatorSuite.GetId()))
	foundComplianceOperatorSuite, exists, err = store.Get(ctx, complianceOperatorSuite.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundComplianceOperatorSuite)
	s.ErrorIs(store.Delete(withNoAccessCtx, complianceOperatorSuite.GetId()), sac.ErrResourceAccessDenied)

	var complianceOperatorSuites []*storage.ComplianceOperatorSuite
	var complianceOperatorSuiteIDs []string
	for i := 0; i < 200; i++ {
		complianceOperatorSuite := &storage.ComplianceOperatorSuite{}
		s.NoError(testutils.FullInit(complianceOperatorSuite, testutils.UniqueInitializer(), testutils.JSONFieldsFilter))
		complianceOperatorSuites = append(complianceOperatorSuites, complianceOperatorSuite)
		complianceOperatorSuiteIDs = append(complianceOperatorSuiteIDs, complianceOperatorSuite.GetId())
	}

	s.NoError(store.UpsertMany(ctx, complianceOperatorSuites))

	complianceOperatorSuiteCount, err = store.Count(ctx)
	s.NoError(err)
	s.Equal(200, complianceOperatorSuiteCount)

	s.NoError(store.DeleteMany(ctx, complianceOperatorSuiteIDs))

	complianceOperatorSuiteCount, err = store.Count(ctx)
	s.NoError(err)
	s.Equal(0, complianceOperatorSuiteCount)
}
