// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"fmt"
	"reflect"

	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/features"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
	"github.com/stackrox/rox/pkg/sac/resources"
)

var (
	// CreateTableComplianceOperatorSuitesStmt holds the create statement for table `compliance_operator_suites`.
	CreateTableComplianceOperatorSuitesStmt = &postgres.CreateStmts{
		GormModel: (*ComplianceOperatorSuites)(nil),
		Children:  []*postgres.CreateStmts{},
	}

	// ComplianceOperatorSuitesSchema is the go schema for table `compliance_operator_suites`.
	ComplianceOperatorSuitesSchema = func() *walker.Schema {
		schema := GetSchemaForTable("compliance_operator_suites")
		if schema != nil {
			return schema
		}
		schema = walker.Walk(reflect.TypeOf((*storage.ComplianceOperatorSuite)(nil)), "compliance_operator_suites")
		referencedSchemas := map[string]*walker.Schema{
			"storage.Cluster": ClustersSchema,
		}

		schema.ResolveReferences(func(messageTypeName string) *walker.Schema {
			return referencedSchemas[fmt.Sprintf("storage.%s", messageTypeName)]
		})
		schema.ScopingResource = resources.ComplianceOperator
		RegisterTable(schema, CreateTableComplianceOperatorSuitesStmt, features.ComplianceEnhancements.Enabled)
		return schema
	}()
)

const (
	// ComplianceOperatorSuitesTableName specifies the name of the table in postgres.
	ComplianceOperatorSuitesTableName = "compliance_operator_suites"
)

// ComplianceOperatorSuites holds the Gorm model for Postgres table `compliance_operator_suites`.
type ComplianceOperatorSuites struct {
	Name       string `gorm:"column:name;type:varchar;primaryKey"`
	ClusterID  string `gorm:"column:clusterid;type:varchar;primaryKey"`
	Serialized []byte `gorm:"column:serialized;type:bytea"`
}
