{{- if ._rox._crsManifest }}
{{- $crs := ._rox._crsManifest -}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-registration-secret
  namespace: {{ ._rox._namespace | quote }}
  labels:
    {{- include "srox.labels" (list . "secret" "cluster-registration-secret") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "cluster-registration-secret") | nindent 4 }}
type: Opaque
data:
  crs: {{ dig "data" "crs" "" $crs | quote }}
{{- end }}